flush_interval = "100ms"
metric_level = "Info"
compression_codec = "Zstd"
l0_sst_size_bytes = 134217728

[compactor_options]
max_concurrent_compactions = 16

[compactor_options.worker]
max_concurrent_compactions = 16
max_sst_size = 134217728
max_subcompactions = 1
