l0_max_ssts = 32
l0_max_ssts_per_key = 32
l0_flush_parallelism = 16
max_unflushed_bytes = 2147483648
wal_enabled = false

[compactor_options]
poll_interval = "1s"

[compactor_options.worker]
bytes_to_fetch = 8388608
compactions_poll_interval = "1s"

[compactor_options.scheduler_options]
max_compaction_sources = "16"

[object_store_cache_options]
part_size_bytes = 1048576
