l0_max_ssts = 64
l0_max_ssts_per_key = 32
max_unflushed_bytes = 2147483648
wal_enabled = false

[compactor_options]
poll_interval = "250ms"

[compactor_options.worker]
bytes_to_fetch = 8388608
compactions_poll_interval = "250ms"
max_fetch_tasks = 8

[object_store_cache_options]
part_size_bytes = 1048576
cache_on_flush = true
