flush_interval = "10ms"
metric_level = "Info"
manifest_poll_interval = "20ms"
l0_sst_size_bytes = 65536
max_unflushed_bytes = 8388608

[compactor_options]
poll_interval = "20ms"
commit_compacted_interval = "20ms"

[compactor_options.worker]
compactions_poll_interval = "20ms"
